import softScroll from "./modulos/scroll-suave.js";
import animationOnScroll from "./modulos/animacao-scroll.js";
import initAccordion from "./modulos/accordion.js";
import initTabNav from "./modulos/tabNav.js";
import initModal from "./modulos/modal.js";
import initToolTip from "./modulos/tooltip.js";
import initDropdownMenu from './modulos/dropdown.js';
import initMenuMobile from './modulos/menu-hamburger.js';
import initAnimarNumeros from './modulos/numeros.js';
import initFuncionamento from './modulos/funcionamento.js';
softScroll();
animationOnScroll();
initAccordion();
initTabNav();
initModal();
initToolTip();
initDropdownMenu();
initMenuMobile();
initAnimarNumeros();
initFuncionamento();
